### ISSUE TITLE
Library is not compatible with Serilog.Sinks.Http 8.0.0

### ISSUE THREAD

**Issue by isaevdan** [serilog-contrib/Serilog.Sinks.Logz.Io#30]
Error appears when library Serilog.Sinks.Http with version 8.0.0 directly referenced in project

```
Unhandled exception. System.TypeLoadException: Could not load type 'Serilog.Sinks.Http.BatchFormatters.BatchFormatter' from assembly 'Serilog.Sinks.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(QCallAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Serilog.Settings.Configuration.ConfigurationReader.<>c.<FindConfigurationExtensionMethods>b__32_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Serilog.Settings.Configuration.ConfigurationReader.FindEventEnricherConfigurationMethods(IReadOnlyCollection`1 configurationAssemblies)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyEnrichment(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
```

Note: BatchFormatter was removed in latest version of library

**Comment by mantasaudickas** [comment]
Updates are now released with v7.0.0
